  <footer>
    <div class="container">
      <div class="strapline">
          <p>The Natural Resource Governance Institute promotes the effective, transparent and accountable management of oil, gas and mineral resources for the public good.</p>
      </div>
      <div class="row">
        <div class="span4">
          <h2 class="block-title">Links</h2>
          <ul class="unstyled"><li><a href="http://www.resourcegovernance.org/">Natural Resource Governace Institute (Main Website)</a></li></ul>
        </div>
        <div class="span4">
          <h2 class="block-title">Block 2</h2>
        </div>
        <div class="span4">
          <h2 class="block-title">Block 3</h2>
        </div>
      </div>
    </div>
  </footer>

  </body>
</html>
